# Generated by Django 3.0.1 on 2020-02-14 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataScience',
        ),
        migrations.DeleteModel(
            name='Development',
        ),
    ]
