# Generated by Django 3.0.1 on 2020-02-17 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_bootstrap_css_html_machine_php_python_rtool_stat_wordpress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bootstrap',
            old_name='bs_question',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='css',
            old_name='css_question',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='html',
            old_name='html_question',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='machine',
            old_name='ml_question',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='php',
            old_name='php_question',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='python',
            old_name='py_question',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='rtool',
            old_name='r_question',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='stat',
            old_name='st_question',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='wordpress',
            old_name='wp_question',
            new_name='question',
        ),
    ]
